name: C/C++ CI

on: [push]
  

jobs:
  check-bats-version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compilation de server
      run: cd server
    - run: gcc pserver.c -o pserver
    - run: ./pserver
    - name: compilation de client
      run: cd client
    - run: gcc pclient.c -o pclient
    - run: ./pclient peg 0.0.0.0
