name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - run: cd server
    - name: make check
      run: make run-server
    - name: make distcheck
      run: make distrun-server
    - run: cd client
    - run: make run-cli file=peg
    - run: make distrun-cli
