name: C/C++ CI

on: [push]

jobs:
  check-bats-version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compilation and execution server
      run: cd server
    - run: make run-server
    - name: compilation and execution client
      run: client
    - run: make run-cli file=peg
