name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compilation and execution server
      run: make run-server
    - name: compilation and execution client
      run: make run-cli file=server/pic

